services:
  - type: web
    name: health-risk-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT  
        value: 587
      - key: MAIL_USE_TLS
        value: true
